#ifndef __F_IPTV_MPLAYER_H__
#define __F_IPTV_MPLAYER_H__

typedef enum {
	F_IPTV_MP_MODE_STOP = 0,
	F_IPTV_MP_MODE_PAUSE,
	F_IPTV_MP_MODE_NORMAL_PLAY,
	F_IPTV_MP_MODE_TRICK
} f_iptv_mp_mode_e;

typedef enum {
	F_IPTV_MP_RTSP_CONNECT_FAILED = 1,
	F_IPTV_MP_RTSP_SEND_FAILED,
	F_IPTV_MP_RTSP_READ_FAILED,
	F_IPTV_MP_RTSP_CONNECTION_DIED,
	F_IPTV_MP_RTSP_STATUS_LINE,
	F_IPTV_MP_RTSP_STATUS_PLAYING,
	F_IPTV_MP_RTSP_STATUS_ANNOUNCE,
	F_IPTV_MP_RTSP_STATUS_END_OF_STREAM,
	F_IPTV_MP_RTSP_STATUS_NOT_FOUND,
	F_IPTV_MP_RTSP_STATUS_NO_VIDEO,
	F_IPTV_MP_IGMP_STATUS_END_OF_STREAM,
	F_IPTV_MP_RTSP_CONNECT_STOPPED,
	F_IPTV_MP_RTSP_STATUS_AUTHENTICATE,
	F_IPTV_MP_RTSP_STATUS_REDIRECTED,
	F_IPTV_MP_IGMP_STATUS_PLAYING,
	F_IPTV_MP_UDP_STATUS_END_OF_STREAM,
	F_IPTV_MP_UDP_STATUS_PLAYING,
	F_IPTV_MP_MP3S_STATUS_END_OF_STREAM,
	F_IPTV_MP_AUD_DESCRIP_READY,
	F_IPTV_MP_RTSP_STATUS_START_OF_STREAM,
	F_IPTV_MP_MP3S_STATUS_START_OF_STREAM,
	F_IPTV_MP_RTSP_STATUS_ANNOUNCE_PARTIAL,
	F_IPTV_MP_STATUS_PMT_CHANGED,
	F_IPTV_MP_PVRS_STATUS_PLAYING,
	F_IPTV_MP_PVRS_STATUS_END_OF_STREAM,
	F_IPTV_MP_RTSP_STATUS_SET_PARAMETER,
	F_IPTV_MP_RTSP_STATUS_INVALID_RANGE,
} f_iptv_mp_error_e;

typedef enum {
	F_IPTV_DIS_SET = 0,
	F_IPTV_DIS_FULLSCREEN,
	F_IPTV_DIS_WIDTH,
	F_IPTV_DIS_HEIGHT,
	F_IPTV_DIS_CLOSE = 255
} f_iptv_dismode_e;

#endif
