#ifndef __F_IPTV_LIMIT_H__
#define __F_IPTV_LIMIT_H__

#define F_IPTV_MAX_JSON_SIZE     	1024
#define F_IPTV_USR_TOKEN_LEN        	32
#define F_IPTV_ENC_TOKEN_LEN 		36
#define F_IPTV_ENC_BUFF_SIZE            512
#define F_IPTV_GROUP_NUMBER_LEN 	8
#define F_IPTV_HOTKEY_SIZE 		256
#define F_IPTV_SHARE_KEY_SIZE       	25
#define F_IPTV_STBID_LEN 		32
#define F_IPTV_TYPE_LEN 		10
#define F_IPTV_SESSION_ID_SIZE 		256
#define F_IPTV_DOMAIN_SIZE		256
#define F_IPTV_URL_SIZE             	256
#define F_IPTV_SERURL_LEN           	256
#define F_IPTV_SERUSR_NAME_LEN      	256
#define F_IPTV_SERPASSWD_LEN        	256
#define F_IPTV_PLATFORM_CODE_LEN    	10
#define F_IPTV_TIMESTR_SIZE         	2
#define F_IPTV_INFO_STR_SIZE        	256
#define F_IPTV_PRODUCT_NAME_SIZE       	16
#define F_IPTV_MANUFACTURE_SIZE       	32
#define F_IPTV_MANUFACTURE_OUI_SIZE    	16
#define F_IPTV_SERVER_PARAM_LEN         32
#define F_IPTV_KEY_NAME_SIZE            32
#define F_IPTV_KEY_EVENT_TYPE_SIZE      32


#define N_IPTV_CHANNEL_ID_LEN   32
#define N_IPTV_CHANNEL_NAME_LEN 32
#define N_IPTV_CHANNEL_URL_LEN  1024
#define N_IPTV_CHANNEL_TYPE_LEN 16
#define N_IPTV_CHANNEL_IP_LEN   40

#define F_TR069_LAN_MAX_DIAG_STATE_STR_SIZE       32
#define F_TR069_LAN_MAX_DIAG_REP_NUM_SIZE         16
#define F_TR069_LAN_DIAG_TIME_SIZE                16
#define F_TR069_LAN_DIAG_DATA_BLOCK_SIZE          8
#define F_TR069_LAN_DIAG_DSCP_SIZE                8
#define F_TR069_LAN_DIAG_RESULT_CNT_SIZE          16
#define F_TR069_STBSERV_PROTOCOL_SIZE             32
#define F_TR069_STBSERV_STANDARD_LEN              256
#define F_TR069_DEVINFO_PRODUCT_NAME_LEN     	  64
#define F_TR069_DEVINFO_MANUFACTURER_NAME_LEN     64
#define F_TR069_DEVINFO_MANUFACTURER_OUI_LEN      6
#define F_TR069_DEVINFO_PRODUCT_CLASS_NAME_LEN    64
#define F_TR069_DEVINFO_SN_LEN                    64
#define F_TR069_DEVINFO_PROV_CODE_LEN             64
#define F_TR069_DEVINFO_STATUS_LEN                64
#define F_TR069_IPTV_FRAME_LOST_CNT_SIZE          5
#define F_TR069_IPTV_PACK_LOST_CNT_SIZE           10
#define F_TR069_IPTV_RATE_STR_SIZE                10
#define F_TR069_ENABLE_SIZE                       16
#define F_TR069_STRING_INFO_SIZE                  1024
#define F_TR069_NUMBERCNT_SIZE                    16
#define F_TR069_MANAGMENT_UPGRADE_MANAGED_SIZE    16
#define F_TR069_MANAGMENT_PARAM_KEY_LEN           32

#endif
