/*
*
*this error code list is suited to IPTVS_2_2_JS_ZTE
*
*/
#ifndef __ERRORCODE_H__
#define __ERRORCODE_H__


/*********start net error code***********/
#define ERRORCODE_START_SERVER_DISCONNECT  "D1302"
#define ERRORCODE_START_DHCP_DISCONNECT "D1305"
#define ERRORCODE_START_DEVICE_ABNORMAL "D1306"

#define ERRORCODE_START_PPPOE_DSLAMANDBAS_REFUSE "A1401"
#define ERRORCODE_START_PPPOE_BAS_NOACK "A1402"
#define ERRORCODE_START_PPPOE_IDANDPW_ERROR "A1403"
#define ERRORCODE_START_PPPOE_TIMEOUT "A1404"

#define ERRORCODE_START_NET_DEVICE_DISCONNECT "N1901"
#define ERRORCODE_START_WIRELESS_DEVICE_DISCONNECT "N1902"
#define ERRORCODE_START_WIRELESS_AP_DISCONNECT "N1903"




#endif

